### PR TITLE
fix static resources on home page when using --nosearchbar

### LINKED ISSUE #186: Invalid static resources on main page when --nosearchbar is used
`./kiwix-serve --nosearchbar --port 8091 --library /var/tmp/kiwix-library.xml --urlRootLocation /offline_sites`

Navigate to http://IP:8091/offline_sites, the page is displayed, but the source shows links to invalid static resources

```html
  <meta charset="UTF-8" />
  <title>Welcome to Kiwix Server</title>
  <script type="text/javascript" src="__ROOT_LOCATION__/skin/jquery-ui/external/jquery/jquery.js"></script>
  <script type="text/javascript" src="__ROOT_LOCATION__/skin/jquery-ui/jquery-ui.min.js"></script>
  <link type="text/css" href="__ROOT_LOCATION__/skin/jquery-ui/jquery-ui.min.css" rel="Stylesheet" />
  <link type="text/css" href="__ROOT_LOCATION__/skin/jquery-ui/jquery-ui.theme.min.css" rel="Stylesheet" />
  <style>
```

### PR DESCRIPTION
**Pull request by swiftugandan**
fixes #186

### CODE REVIEW

File: src/server/kiwix-serve.cpp [hunk 1]
```diff
@@ -161,9 +161,9 @@ void introduceTaskbar(string& content, const string& humanReadableBookId)
              humanReadableBookId,
              "__CONTENT__"));
     }
-    content = replaceRegex(content, rootLocation, "__ROOT_LOCATION__");
     content = replaceRegex(content, replaceRegex(humanReadableBookId, "%26", "&"), "__CONTENT_ESCAPED__");
```
Comment (mgautierfr) [inline src/server/kiwix-serve.cpp]: I would move the both lines out of the `if`.
Even if we don't need to replace `__CONTENT_ESCAPED__` for now, by moving the line out of the `if`, we prevent us against future bug when we will update static resources and add a `__CONTENT_ESCAPED__`

**Comment by mgautierfr** [comment]
This PR is far better than the previous one :)
Please correct your PR accordingly to my other comment and we should be ok.

**Comment by mgautierfr** [comment]
Thanks for your PR !
